### ISSUE TITLE
finalize method

### ISSUE THREAD

**Issue by KaRkY** [BennyQBD/3DGameEngine#5]
Just watched episode 52 and saw you using finalize method. There is a rule in java never use finalize because finalize is not guaranteed to be called. Rather use destroy or close ore something like that and handle freeing resources manually.

**Comment by BennyQBD** [comment]
I realize I wasn't clear enough about this, and I'm going to talk more about it in video 53, but here's the just of it:

-When you allocated resources in OpenGL, they're added to a GLContext. When you deallocate resources, they're removed from the GLContext.
-When you delete the GLContext, all resources attached to it are freed.
-LWJGL deletes the GLContext in the Display.destroy() function.

Since the engine calls Display.destroy() at the end of the program, all resources are ultimately deallocated regardless of what finalize does. The point of the finalize system is for something like when you're playing level1 and then you go to level2. It doesn't matter too much that level1 is still in memory, but it'd be nice if it could be deleted in the background. That's what the finalize system is all about: Just freeing unneeded resources in the background, not the be-all end-all resource collection system.

If that or video 53 doesn't address your concern with the finalize, let me know and I'll be happy to try and resolve the problem.

**Comment by KaRkY** [comment]
Ok I understand your point and partially agree. But consider the case when you load level1 play through level1 and start loading level2 while you are loading level2 you could run out of GPU memory because level1 is still in GPU memory(remember GC doesn’t collect classes right away).

I would say that this method is good enough for tutorial purposes but in real application this kind of resources should be handled manually. Maybe when level ends you call destroy on scene graph and every node is responsible for unloading resources.

**Comment by BennyQBD** [comment]
I see your point, but I think that's more an issue with my example rather than the system itself, wouldn't you agree?

In practice, of course you'll probably want to manually flush the scene graph and delete everything when you load the next level (except maybe if it's some sort of hub system where you freely move between levels). The finalize system is really more targeted towards smaller things like once all of a certain type of enemy is killed and removed from the level, it can be freed from memory. I just brought up levels because I thought it would be an easily understood example.

As for the GPU memory issue, isn't that basically the same as arguing that Java programs can run out of RAM because they can allocate more memory before the garbage collector deletes it, or am I missing something?

Either way, it's a non-issue: If you allocate more memory than is available in one medium, like GPU memory, then it allocates it in RAM or elsewhere. Again, in practice if something consumes a considerable amount of GPU memory and you know when it's removed from the game, then yeah you'd probably delete it manually. The finalize system is more targeted toward smaller things.

Does that clear things up? Am I still missing something?

**Comment by KaRkY** [comment]
GPU memory issue is not the same because GC will run when it is low on RAM, but it can't know when GPU RAM is low.

As for using finalize for other smaller things it's good enough but not perfect.

**Comment by BennyQBD** [comment]
In that case, issue closed unless there's something else you wish to discuss.
