### ISSUE TITLE
Mesh-Optimisation

### ISSUE THREAD

**Issue by ghost** [BennyQBD/3DGameEngine#6]
As i was playing around with loading diffent .obj's i recognized some issues:

Loading without the normals works fine, but if i load normals and texCoords I get some problems with indexing i guess.
So all faces have their own normals. and you can see the single quads.

If I load with texCoords and without normals I get these edges in the reflections.

Laoding with normals and without texCoord does not even work: the texCoord is between the two "/", but if there is none it tries to parse an empty String.

The first two Issues could be caused by me by exporting the obj not properly.
If someone needs Images i can upload some.

**Comment by BennyQBD** [comment]
-If you're loading with normals and texCoords and getting flat shading, it's probably because you're exporting the mesh with flat shading. I don't know what 3D editor you're using, but in Blender if you select "smooth" shading before exporting with normals, there is no flat shading issue as far as I could produce.

-For loading with texCoords and without normals, there will be some slight artifacts simply because the calculated normals are an approximation. There's no way to know exactly what the normals should be unless the model was exported with them. Let me know if you still see artifacts when you're loading normals: If it happens then, then there may be an issue.

-OBJ supports several things such as multiple objects in a file or loading files with normals and no texCoords that I chose not to handle in my OBJ loader. I did this because I'm trying to make this a tutorial on a 3D engine, not on how the OBJ format works, so I'm trying to strike that balance where it supports enough of the format to be useful while not spending so much time on it that it bogs down the videos. If you need individual features like that, I hope it's clear enough how it can be achieved at this point, but I'd really rather not spend more video time on all the tiny nuances of the format if I've already got the idea across.

**Comment by ghost** [comment]
Ok I will try the options for exporting you mentioned. 
I think I will eventually extend your loader if you do not any more.
Anyway thanks for your answer

**Comment by BennyQBD** [comment]
In that case, issue closed unless there's something else you wish to discuss.
